language: node_js
node_js: '8'
script: npm run build
deploy:
  provider: s3
  access_key_id:
    secure: BjvIK852uI1CArsXgSGndOinefNKL35uVFUN6n84LqQ8bqmaV1lJdR3DVGl1cGDMr3jRB0bC8TVyDdy6bAPPQFeXXghzmblmckqVqX5Adkk6mocpgZOm9ndXGUUizKtDJW/4v6ft6GlYKxqknYPncTL5c1tfKQD2/5Cvpbc6WlZS5Bu1K17ONcauOLM+eZTIsMyVYN0gkuUvkLplhDW5+kSK1RXSrGMudVcx5joqVnOlgtCnaulEZkyr0CIYS9MlWiuOOqtGQjOr8kTVgE6MBHxNSewrwCxRIFEyifHVaXqmp2o+PjOap5ORotoCz25ajQ9aq/NskcS1lZAHbz959KmSRx3dzj6z+RVul1dsM1Q0gxD90L+VvzE84QVZF1n7Wky8xPJ8E/yjxZrwjY52YfAuPRWuZ3KHYcM2J3mf6Y7WnEtO0byaKAkY/LqpjxAJOcQMvQyYLmxly/sWeXHdyVUy6XFZtkENnoQ0n6D/tpbE1l5ZBL/rAcmUFR/Q/3jfVH5U4NE50/DdpGCUZyqgRtFOquctnEHndD0ACLVZYZWm18UBGC5FAN2tbKAx7gDVixOPLi19EdLz9uPZ2z4gv9IrDb3FyyguS6w3TLsw1Guyn2kxWH4DBpLgTv6Dcx+HGay9A4pfatOmVMebxtxtQk3jXm4q0k7uG8fd101K88g=
  secret_access_key:
    secure: j7b1uCok+eOV92jrn3mGEkSA8dsZ8ol+x/Q4c4HEijYg++R11t3fuyZDinkgaQm+hUmgqG+POCIXxXqC04rQZRnGkzHW9NiulgA0Dk7O7UsZdTzlbM+GbWeY3gp3Z+G+5vTFKaSMGJbeE9t9TaH77BUHzQig0SGLwi6g5tesqsuu6rg+3x6wAPb5Pe66yj8WbIA1VSxk2iTLtFy2cVurP7FNzcVI9ikPXwcBTCM5Kc2VpVirmIT1hIvwmmIHvS6XZUbEE2g4i7K6a8A07It5u4LjFYyfh/3lTjlihQ1mvbaII8hrnTL8xJV1V8xjx2Nf9k3A3kRV7zHKFN+SRy3F0m1PuYTAPfkaV5R+NcfPGxrHG37fFzIEuTdDFuTJOWuFEgnyJwD07pg8FvL9ovm2JfJmEdLUni6s3ghPN1aO/j94YFM+Aa3dWIL973ayF3nGU45l/vXsV31FYqAVrm8qjSGOYiHZ4r9xN4BvRYLWhWoQH4Otbhy341TYCLgvcYTHHTlxzoC0Su6QRFOWk0BMHjKyPJSeUwksCbisgQMPmVPe2ymQ7IwQb1yC/zEwnRPBl3vGAz8ffTMXUW+8e/z3myHamFl66l74ozRj8+jgtv2Pi+n/fLwLfGy1tkHuSeGdgG7dYwcENLTqEUWJw+a8qFVb5dRxXE2Pg4DjVAf1G0Y=
  bucket: cadastro.projetoincluir.net
  region: sa-east-1
  local_dir: dist
  skip_cleanup: true
  on:
    repo: ProjetoIncluirUFMG/CadastroFrontEnd
    branch: master
